//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SMaP_APP.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class RequestMessage : IBaseModel
    {
        public int ID { get; set; }
        public System.DateTime Created { get; set; }
        public int SenderID { get; set; }
        public string RequestMessage1 { get; set; }
        public int RequestID { get; set; }
        public bool Deleted { get; set; }
    
        public virtual ServiceRequest ServiceRequest { get; set; }
        public virtual Student Student { get; set; }
    }
}
