//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SMaP_APP.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Semester : IBaseModel
    {
        public Semester()
        {
            this.SessionGroup = new HashSet<SessionGroup>();
        }
    
        public int ID { get; set; }
        public string SemesterName { get; set; }
        public int SemesterType { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public System.DateTime StartDate { get; set; }
        public System.DateTime EndDate { get; set; }
        public bool Deleted { get; set; }
    
        public virtual Dictionary Dictionary { get; set; }
        public virtual ICollection<SessionGroup> SessionGroup { get; set; }
    }
}
