//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SMaP_APP.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class ServiceStoreServiceParams : IBaseModel
    {
        public int ID { get; set; }
        public int ParentServiceStoreID { get; set; }
        public int ParamServiceStoreID { get; set; }
        public bool Deleted { get; set; }
    
        public virtual ServiceStore ServiceStore { get; set; }
        public virtual ServiceStore ServiceStore1 { get; set; }
    }
}
