//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SMaP_APP.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class SessionGroup : IBaseModel
    {
        public SessionGroup()
        {
            this.Student = new HashSet<Student>();
            this.Teacher1 = new HashSet<Teacher>();
            this.Team = new HashSet<Team>();
        }
    
        public int ID { get; set; }
        public string SessionGroupName { get; set; }
        public Nullable<int> SemesterID { get; set; }
        public Nullable<int> Teacher { get; set; }
        public bool Deleted { get; set; }
    
        public virtual Semester Semester { get; set; }
        public virtual ICollection<Student> Student { get; set; }
        public virtual ICollection<Teacher> Teacher1 { get; set; }
        public virtual ICollection<Team> Team { get; set; }
    }
}
