//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SMaP_APP.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Team : IBaseModel
    {
        public int ID { get; set; }
        public int SessionGroupID { get; set; }
        public string TeamName { get; set; }
        public Nullable<int> TeamCaptain { get; set; }
        public bool Deleted { get; set; }
    
        public virtual SessionGroup SessionGroup { get; set; }
        public virtual Student Student { get; set; }
    }
}
